### ISSUE TITLE
Possible escaping issue in package links?

### ISSUE THREAD

**Issue by tbenthompson** [jorenham/jax_pep503#4]
I'm not sure if this is the source of the problem, but it seems like I'm not able to install any of the package versions that have a "+" in the version. e.g. "0.4.4+cuda11.cudnn86"

<img width="568" alt="2023-03-01 16 24 39@2x" src="https://user-images.githubusercontent.com/4241811/222268296-3d742329-ca14-421d-a4c7-80a4a84a717a.png">

**Comment by jorenham** [comment]
That looks like a job for `url.parse.unquote`

**Comment by jorenham** [comment]
@tbenthompson It should be fixed now
